version: "3.2"

services:  
  traefik:
    image: traefik:1.7-alpine
    container_name: project_traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=${WEBSITE_DOMAIN}"
      - "--acme=false"
      - "--acme.acmelogging=true"
      - "--acme.email=webmaster@${WEBSITE_DOMAIN}"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./services/traefik/acme.json:/acme.json"
      - "./services/traefik/data:/traefik/acme/account"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  db:
    image: postgres
    ports:
     - 5432:5432
    env_file:
      - ".env"
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:4.0-alpine
    container_name: project_redis
    restart: unless-stopped

  project:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./project:/project/project
    labels:
      - "traefik.enable=true"
      - "traefik.port=8120"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host: ${WEBSITE_DOMAIN}"
      - "traefik.docker.network=${WEBSITE_DOMAIN}"
    env_file:
      - ".env"
    command: bash -c 'service nginx start; cd /project; PYTHONIOENCODING="utf-8" python3 manage.py collectstatic --noinput --settings=project.envs.dev; honcho start -f Procfile.dev'
    tty: true
    stdin_open: true
    restart: unless-stopped

networks:
  default:
    external:
      name: "${WEBSITE_DOMAIN}"

volumes:
  traefik:
    driver_opts:
      type: none
      device: /root/server-docker-images/data/traefik
      o: bind
  